[package]
name = "ccheckers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nannou = "0.18.1"
nannou_egui = "0.5.0"
strum = "0.24.1"
strum_macros = "0.24.3"
